# Generated by Django 5.2.1 on 2025-05-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.TimeField()),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('first_two_digits', models.CharField(max_length=2)),
                ('last_two_digits', models.CharField(max_length=2)),
                ('color', models.CharField(max_length=7)),
            ],
            options={
                'unique_together': {('date', 'time_slot', 'row', 'column')},
            },
        ),
    ]
